version: "3.8"

services:
  # new-frontend:
  #   image: devhaxcodes/autoapply-new-frontend:${TAG:-prod}
  #   ports:
  #     - "3001:80"

  #   depends_on:
  #     - backend
  backend:
    image: devhaxcodes/autoapply-backend:${TAG:-prod}
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - HEADLESS=true
      - PYTHONUNBUFFERED=1
    shm_size: '4gb' # Required for Chromium browser automation in Docker

  frontend:
    image: devhaxcodes/autoapply-frontend:${TAG:-prod}
    ports:
      - "3000:3000"

    depends_on:
      - backend

  # frontend-revamp:
  #   image: devhaxcodes/autoapply-frontend-revamp:${TAG:-prod}
  #   ports:
  #     - "3002:3000"

  #   depends_on:
  #     - backend

  rss-poller:
    image: devhaxcodes/autoapply-backend:${TAG:-prod}
    command: python poll_worker.py
    volumes:
      - ./data:/app/data
    environment:
      - HEADLESS=true
      - PYTHONUNBUFFERED=1
    depends_on:
      - backend

  job-processor:
    image: devhaxcodes/autoapply-backend:${TAG:-prod}
    command: python automation_worker.py
    volumes:
      - ./data:/app/data
    environment:
      - HEADLESS=true
      - PYTHONUNBUFFERED=1
    shm_size: '4gb'
    depends_on:
      - backend
