version: "3.8"

services:
  new-frontend:
    build:
      context: ./new-frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - HEADLESS=true
      - PYTHONUNBUFFERED=1
      - HOST_PROJECT_ROOT=${HOST_PROJECT_ROOT}
    shm_size: '4gb' # Required for Chromium browser automation in Docker

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

  frontend-revamp:
    build:
      context: ./frontend-revamp
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
