version: "3.8"

services:
  # new-frontend:
  #   build:
  #     context: ./new-frontend
  #     dockerfile: Dockerfile
  #   image: devhaxcodes/autoapply-new-frontend:${TAG:-latest}
  #   ports:
  #     - "3001:80"


  #   depends_on:
  #     - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: devhaxcodes/autoapply-backend:${TAG:-latest}
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - HEADLESS=true
      - PYTHONUNBUFFERED=1
    shm_size: '4gb' # Required for Chromium browser automation in Docker

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: devhaxcodes/autoapply-frontend:${TAG:-latest}
    ports:
      - "3000:3000"


    depends_on:
      - backend

  # frontend-revamp:
  #   build:
  #     context: ./frontend-revamp
  #     dockerfile: Dockerfile
  #   image: devhaxcodes/autoapply-frontend-revamp:${TAG:-latest}
  #   ports:
  #     - "3002:3000"


    # depends_on:
    #   - backend

  rss-poller:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: devhaxcodes/autoapply-backend:${TAG:-latest}
    command: python poll_worker.py
    volumes:
      - ./data:/app/data
    environment:
      - HEADLESS=true
      - PYTHONUNBUFFERED=1
    depends_on:
      - backend
